apiVersion: v1
kind: ConfigMap
metadata:
  name: es-config
  namespace: {{ .Values.namespace }}
data:
  elasticsearch.yml: |
    cluster.name: my-es
    # node.name: dev-es-kibana
    bootstrap.memory_lock: false
    network.host: 0.0.0.0
    http.port: 9200
    action.auto_create_index: .monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*,spans*
    path.data: /data
    search.max_open_scroll_context: 10000
    cluster.routing.allocation.disk.threshold_enabled=false