apiVersion: v1
kind: Service
metadata:
  name: jaeger-collector
  namespace: {{ .Values.global.namespace }}
  labels:
    app: jaeger
spec:
  ports:
    - name: query-http
      port: 16686
      protocol: TCP
      targetPort: 16686
{{- if eq .Values.jaejer.serviceType "NodePort" }}
      nodePort: {{ .Values.jaejer.nodePort }}
{{- end }}
    - name: service-http
      port: 4317
      protocol: TCP
      targetPort: 4317
  selector:
    app: jaeger
  type: {{ .Values.jaejer.serviceType }}
