# Default values for lunettes.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# share
namespace: lunettes
imagePullPolicy: IfNotPresent
kubernetesSvcHost: kubernetes.default
cluster: staging
esUser: elastic
esPassword: changeme

# audit-apiserver
enableAuditApiserver: false
auditResources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 10Mi
auditLogMaxAge: 1
auditLogMaxBackup: 2
auditLogMaxSize: 200

# lunettes
lunettesImage: lunettes/lunettes:latest
lunettesNodeport: 30880
lunettesType: LoadBalancer
apiserverEnabled: true
traceEnable: false
lunettesResources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 500M
    memory: 500Mi

# grafanadi
grafanadiInitKubeClient: false
grafanadiType: LoadBalancer
grafanadiNodePort: 30280
grafanadiResources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# grafana
grafanaImage: lunettes/grafana:latest
grafanaType: LoadBalancer
grafanaNodePort: 30180
grafanaResources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# kibana
kibanaImage: docker.elastic.co/kibana/kibana:6.6.0
kibanaNodePort: 30610
kibanaResources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# filebeat
filebeatImage: elastic/filebeat:6.6.2
filebeatResources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# elasticsearch
elasticImage: docker.elastic.co/elasticsearch/elasticsearch:6.6.0
elasticInitImage: busybox:stable
elastic1NodePort: 30920
elastic2NodePort: 30930
esJavaOptions: "-Xms1g -Xmx1g"
elasticsearchResources:
  limits:
    cpu: 4
    memory: 4G
  requests:
    cpu: 1
    memory: 1G

# prometheus
promImage: prom/prometheus
prometheusNodePort: 30190
prometheusResources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 100Mi

# jaejer
jaegerImage: quay.io/jaegertracing/all-in-one:1.45
jaegerType: LoadBalancer
jaegerNodePort: 30686
jaegerResources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 100Mi
