name: 'Convert images to lunettes'
on:
  push:
    branches:
    - main
    paths:
    - 'hack/convert-image/**'
  workflow_dispatch:

env:
  ACR_REGISTRY: registry.cn-hangzhou.aliyuncs.com
  DOCKERHUB_REGISTRY: docker.io
  TARGET_NAMESPACE: linuzb

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # git checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # 登录 acr https://cr.console.aliyun.com/cn-hangzhou/instance/repositories
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      # 登录 dockerhub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.ACR_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        working-directory: ./src/transform-images 
        run: |
          chmod +x convert_images.sh
          ./convert_images.sh ${{ env.ACR_REGISTORY }}/${{ env.TARGET_NAMESPACE }}
          ./convert_images.sh ${{ env.DOCKERHUB_REGISTORY }}/${{ env.TARGET_NAMESPACE }}
